language: python
python:
  - "3.6"
install:
  - make deps
script:
  - make lint
  - make test
  - make docker_build
  - make docker_push
serivices:
  - docker

deploy:
  provider:heroku
  app: pacific-plains-83932
  api_key: ${HEROKU_API_KEY}
